SET @LOGIN_ID=SELECT VAL FROM CONSTANT WHERE NAME = 'ACTIVE_LOGIN_ID';

MERGE INTO HISTORY(LOGIN_ID, CREATED_AT, STATUS, ERROR, ORDER_ID, OPERATION_TYPE)
    KEY(LOGIN_ID) VALUES (@LOGIN_ID, CURRENT_TIMESTAMP(), 2, 'Error', 1234, 2)